### ISSUE TITLE
Favicon missing in mobile snippet preview in v5.1.0

### ISSUE THREAD

**Issue by eduardofrank** [Yoast/Yoast-SEO-for-TYPO3#296]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

The mobile snippet preview in the backend does not show the favicon. Upon inspection, the path for the favicon looks like this: /typo3conf/ext/mysitepackage/Resources/Public/Icons/favicon.ico" type="image/png" alt="" .
In the console, a 404 error is displayed for the favicon and the above path is shown. Pasting the absolute path in a browser produces a 404. But after stripping " type="image/png", the path works and the favicon is shown.
It seems therefore, that there is a bug in the path construction.
This was observed in a version 9.5.9 multisite setup with two domains running version 5.1.0 of the Yoast SEO plugin. The same observation could be confirmed in both domains.

The proper behavior would have been that the favicon would appear in the mobile snippet preview, like it does in a live search for the same content.

* TYPO3 version: 9.5.9
* Yoast SEO version: 5.1.0
* Relevant extensions in case of a bug:

**Comment by alex-boehm** [comment]
We can confirm this issue.

The problem here is that the double quotes are escaped (`&quot;`) therefore the src attribute is not valid.
This is what we see in our browser:

`<img src="/typo3conf/ext/png_npnh_base/Resources/Public/Img/De/favicon.ico&quot; type=&quot;image/x-icon" alt="" class="sc-cbkKFq cLWmcK">`

**Comment by maechler** [comment]
Could probably be fixed by https://github.com/Yoast/Yoast-SEO-for-TYPO3/pull/325.

**Comment by darthnorman** [comment]
Double quotation is not a problem here, using v7.0.0 and it still doesn't work because getting the base url fails.
`https://wsw-online.dmk.dev/wsw-mobil/fahrt-planen/fahrplanwechsel/?L=0/favicon.ico`
This can't be right.

**Comment by twllndr** [comment]
I have the same problem with the mobile preview in the page module. It tries to load "/favicon.ico" - starting from the path of the page where it is loading the content for the preview. So if I'm on the page "www.customer.com/products" yoast_seo tries to load the favicon from "www.customer.com/products/favicon.ico" - which is not correct and results in a 404 in the console.

**Comment by twllndr** [comment]
One addition: I don't know if it's reasonable to search for "/favicon.ico" at all, as a website might have set the favicon with <link rel="icon"> to a completely different file path (with a different file name and file extension).
